-- THESE MUST LINE UP WITH MELEE MOVESETS
--  e.g. 0 ~ X ARE MELEE CONFIGURATIONS
--  AND X + 1 ~ INF ARE THE REST
-- !! SAVE SAFE !!
return {
    SWORD_SHIELD = 1;
    X_SHIELD = 2;

    TWO_HANDED_SWORD = 3;
    SWORD_SWORD = 4;
    SWORD_X = 5;
    SPEAR = 6;




    BOW = 30;
}